// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check_user_by_code.sql

package database

import (
	"context"
	"database/sql"
)

const checkUserByCode = `-- name: CheckUserByCode :one
SELECT id, login, verified, code, code_expires_at, refresh_token, refresh_token_expires_at, created_at, updated_at, deleted_at FROM users
WHERE login = $1 AND code = $2 AND code_expires_at >= NOW() LIMIT 1
`

type CheckUserByCodeParams struct {
	Login string         `json:"login"`
	Code  sql.NullString `json:"code"`
}

func (q *Queries) CheckUserByCode(ctx context.Context, arg CheckUserByCodeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserByCode, arg.Login, arg.Code)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
