// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check_user_by_refresh_code.sql

package database

import (
	"context"
	"database/sql"
)

const checkUserByRefreshCode = `-- name: CheckUserByRefreshCode :one
SELECT id, login, verified, code, code_expires_at, refresh_token, refresh_token_expires_at, created_at, updated_at, deleted_at FROM users
WHERE refresh_token = $1 AND refresh_token_expires_at >= NOW() LIMIT 1
`

func (q *Queries) CheckUserByRefreshCode(ctx context.Context, refreshToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserByRefreshCode, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
