// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(login, code, code_expires_at) VALUES($1, $2, $3)
RETURNING id, login, verified, code, code_expires_at, refresh_token, refresh_token_expires_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Login         string         `json:"login"`
	Code          sql.NullString `json:"code"`
	CodeExpiresAt sql.NullTime   `json:"code_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Login, arg.Code, arg.CodeExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
