// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_user_by_login.sql

package database

import (
	"context"
)

const findUserByLogin = `-- name: FindUserByLogin :one
SELECT id, login, verified, code, code_expires_at, refresh_token, refresh_token_expires_at, created_at, updated_at, deleted_at FROM users
WHERE login = $1 LIMIT 1
`

func (q *Queries) FindUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
