// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type User struct {
	ID                    int64          `json:"id"`
	Login                 string         `json:"login"`
	Verified              sql.NullBool   `json:"verified"`
	Code                  sql.NullString `json:"code"`
	CodeExpiresAt         sql.NullTime   `json:"code_expires_at"`
	RefreshToken          sql.NullString `json:"refresh_token"`
	RefreshTokenExpiresAt sql.NullTime   `json:"refresh_token_expires_at"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
}
