// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckUserByCode(ctx context.Context, arg CheckUserByCodeParams) (User, error)
	CheckUserByRefreshCode(ctx context.Context, refreshToken sql.NullString) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByLogin(ctx context.Context, login string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
