// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_refresh_token.sql

package database

import (
	"context"
	"database/sql"
)

const updateUserRefreshToken = `-- name: UpdateUserRefreshToken :exec
UPDATE users
SET refresh_token = $1,refresh_token_expires_at = $2
WHERE id = $3
`

type UpdateUserRefreshTokenParams struct {
	RefreshToken          sql.NullString `json:"refresh_token"`
	RefreshTokenExpiresAt sql.NullTime   `json:"refresh_token_expires_at"`
	ID                    int64          `json:"id"`
}

func (q *Queries) UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRefreshToken, arg.RefreshToken, arg.RefreshTokenExpiresAt, arg.ID)
	return err
}
