// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package database

import (
	"context"
	"database/sql"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET code = $1, code_expires_at = $2
WHERE id = $3
`

type UpdateUserParams struct {
	Code          sql.NullString `json:"code"`
	CodeExpiresAt sql.NullTime   `json:"code_expires_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Code, arg.CodeExpiresAt, arg.ID)
	return err
}
